### ISSUE TITLE
Sends more than one notification

### ISSUE THREAD

**Issue by fireattack** [BeeeQueue/isthepatchout#312]
![image](https://user-images.githubusercontent.com/4130991/186295627-e028b848-9993-438f-9acc-084aef9575a4.png)

**Comment by BeeeQueue** [comment]
I know, I've turned it off for now

**Comment by BeeeQueue** [comment]
No idea why it happened, no logic has changed 😢

**Comment by BeeeQueue** [comment]
Turns out the issue was updating subscribers last notified patch after sending the notification.

It was trying to update 500 subscriptions at once via the Supabase SDK which uses the REST API with query parameters, and that created a request with a URL around 94000 characters long when the HTTP spec allows 2048...

I swapped out all usages of the JS SDK in the notifications service with normal SQL and added a kill switch in case any subscription does not get updated - leading to an infinite loop.

That should prevent this from happening again.
